const words = [
    { word: "abacaxi", clue: "Fruta tropical" },
    { word: "elefante", clue: "Animal de grande porte com tromba longa" },
    { word: "computador", clue: "Dispositivo eletrônico" },
    { word: "girafa", clue: "Animal alto, com pescoço longo" },
    { word: "chocolate", clue: "Doce feito de cacau" },
    { word: "piano", clue: "Instrumento musical com teclas" },
    { word: "tigre", clue: "Felino selvagem" },
    { word: "esmeralda", clue: "Tipo de pedra preciosa" },
    { word: "navio", clue: "Embarcação no mar" },
    { word: "telefone", clue: "Dispositivo de comunicação" },
    { word: "floresta", clue: "Área com muitas árvores" },
    { word: "quadrado", clue: "Figura geométrica de quatro lados" },
    { word: "foguete", clue: "Veículo espacial" },
    { word: "sorvete", clue: "Doce gelado" },
    { word: "bicicleta", clue: "Veículo de duas rodas" },
    { word: "avião", clue: "Meio de transporte aéreo" },
    { word: "macaco", clue: "Primate arbóreo" },
    { word: "raios", clue: "Descargas elétricas na atmosfera" },
    { word: "montanha", clue: "Elevação natural da terra" },
    { word: "vela", clue: "Objeto para iluminação" },
    { word: "sol", clue: "Estrela que ilumina o sistema solar" },
    { word: "relógio", clue: "Instrumento para medir o tempo" },
    { word: "oceano", clue: "Grande massa de água salgada" },
    { word: "bola", clue: "Objeto esférico usado em esportes" },
    { word: "livro", clue: "Conjunto de páginas encadernadas" },
    { word: "cachorro", clue: "Animal doméstico fiel" },
    { word: "pintura", clue: "Obra de arte feita com tinta" },
    { word: "árvore", clue: "Planta com tronco e copa" },
    { word: "jardim", clue: "Área cultivada com plantas e flores" },
    { word: "carro", clue: "Veículo motorizado de quatro rodas" },
    { word: "chave", clue: "Objeto usado para abrir fechaduras" },
    { word: "cidade", clue: "Área urbana com grande população" },
    { word: "mesa", clue: "Móvel com superfície plana" },
    { word: "computador", clue: "Dispositivo eletrônico para processamento de dados" },
    { word: "lua", clue: "Satélite natural da Terra" },
    { word: "guitarra", clue: "Instrumento musical de cordas" },
    { word: "chaveiro", clue: "Objeto para guardar chaves" },
    { word: "lago", clue: "Corpo de água doce cercado por terra" },
    { word: "folha", clue: "Parte verde das plantas" },
    { word: "café", clue: "Bebida feita com grãos torrados" },
    { word: "blusa", clue: "Peça de roupa para a parte superior do corpo" },
    { word: "computador", clue: "Dispositivo eletrônico de processamento de dados" },
    { word: "janela", clue: "Abertura em uma parede para passagem de luz" },
    { word: "prato", clue: "Objeto para servir alimentos" },
    { word: "música", clue: "Arte de organizar sons e silêncios" },
    { word: "mar", clue: "Grande extensão de água salgada" },
    { word: "poema", clue: "Texto literário em verso" },
    { word: "roda", clue: "Objeto circular que gira" },
    { word: "tela", clue: "Superfície onde se projeta imagem" },
    { word: "caneta", clue: "Objeto para escrever" },
    { word: "porta", clue: "Estrutura que fecha uma entrada" },
    { word: "pintura", clue: "Imagem feita com tinta" },
    { word: "bola", clue: "Objeto redondo usado em esportes" },
    { word: "sol", clue: "Estrela que ilumina o sistema solar" },
    { word: "quadro", clue: "Tela para pintura ou desenho" },
    { word: "computador", clue: "Máquina para processamento de dados" },
    { word: "abajur", clue: "Luminária para iluminação de ambientes" },
    { word: "piscina", clue: "Estrutura para nadar" },
    { word: "cachorro", clue: "Animal doméstico fiel" },
    { word: "bola", clue: "Objeto redondo usado em esportes" },
    { word: "maçã", clue: "Fruta com casca vermelha ou verde" },
    { word: "vento", clue: "Movimento do ar" },
    { word: "teatro", clue: "Local para apresentações de peças" },
    { word: "museu", clue: "Lugar onde se conservam e exibem coleções" },
    { word: "lápis", clue: "Ferramenta de escrita com grafite" },
    { word: "pintura", clue: "Representação visual em uma superfície" },
    { word: "pássaro", clue: "Animal com asas e penas" },
    { word: "mapa", clue: "Representação gráfica de uma área" },
    { word: "chave", clue: "Objeto para abrir fechaduras" },
    { word: "carro", clue: "Veículo motorizado de quatro rodas" },
    { word: "livro", clue: "Conjunto de páginas encadernadas" },
    { word: "prato", clue: "Recipiente para servir alimentos" },
    { word: "futebol", clue: "Esporte jogado com uma bola" },
    { word: "vassoura", clue: "Objeto para varrer" },
    { word: "caneta", clue: "Instrumento para escrever" },
    { word: "avião", clue: "Veículo aéreo" },
    { word: "salada", clue: "Mistura de vegetais crus" },
    { word: "guarda-chuva", clue: "Objeto para proteção contra a chuva" },
    { word: "carroça", clue: "Veículo de tração animal" },
    { word: "relógio", clue: "Instrumento para medir o tempo" },
    { word: "escada", clue: "Estrutura para subir ou descer" },
    { word: "escultura", clue: "Arte de esculpir figuras" },
    { word: "sombra", clue: "Área escura criada por um objeto bloqueando a luz" },
    { word: "banco", clue: "Assento ou instituição financeira" },
    { word: "janela", clue: "Abertura em uma parede para ventilação" },
    { word: "lâmpada", clue: "Fonte de luz artificial" },
    { word: "jardim", clue: "Área cultivada com plantas e flores" },
    { word: "chaveiro", clue: "Objeto para guardar chaves" },
    { word: "viagem", clue: "Deslocamento de um lugar para outro" },
    { word: "telefone", clue: "Dispositivo para comunicação a distância" },
    { word: "blusa", clue: "Peça de roupa para a parte superior do corpo" },
    { word: "sapato", clue: "Calçado para os pés" },
    { word: "forno", clue: "Equipamento para assar alimentos" },
    { word: "martelo", clue: "Ferramenta para bater pregos" },
    { word: "painel", clue: "Superfície para exibir informações" },
    { word: "oculos", clue: "Objeto para correção visual" },
    { word: "balança", clue: "Instrumento para medir peso" },
    { word: "escova", clue: "Ferramenta para limpar ou pentear" },
    { word: "chave", clue: "Dispositivo para abrir ou fechar fechaduras" },
    { word: "tênis", clue: "Calçado esportivo" },
    { word: "fogão", clue: "Equipamento para cozinhar alimentos" },
    { word: "computador", clue: "Máquina eletrônica para processamento de dados" },
    { word: "luz", clue: "Radiação visível que ilumina" },
    { word: "nuvem", clue: "Á gua NO Céu"},
    ];       
  
  export default function getWord() {
    const index = Math.floor(Math.random() * words.length);
    return words[index];
  }